apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventstore.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    helm.sh/chart: {{ include "eventstore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database
data:
  EVENTSTORE_CLUSTER_SIZE: {{ quote .Values.clusterSize }}
  EVENTSTORE_RUN_PROJECTIONS: "All"
  EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
  EVENTSTORE_HTTP_PORT: {{ quote .Values.extHttpPort }}
  EVENTSTORE_INSECURE: {{ quote .Values.insecure }}
  EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"
  EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
  {{- range $setting, $option := .Values.eventStoreConfig }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}

